const demo={schema:"meshfit.benchmark-proof/v1",benchmark_id:"benchmark-001",kit_complete:false,expected_bundles:0,valid_bundles:0,evidence_publishable:false,evidence_status:"REAL CAMPAIGN EVIDENCE PENDING",inputs:[{role:"snapshot",path:"inputs/snapshot.yaml",sha256:"<sha256>"},{role:"target",path:"inputs/target.yaml",sha256:"<sha256>"}],candidates:[{name:"meshfit",plan_id:"<precommitted-plan-id>",benchmark_host:"<real-host>",runtime:"<runtime>",bundles:[]}],report:{note:"Contract demo only. No synthetic measurement is presented as a real result."}};
let current=demo,rawText=JSON.stringify(demo,null,2);
const q=s=>document.querySelector(s);
const esc=v=>String(v??"—").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function yamlScalar(text,key){for(const line of text.split(/\r?\n/)){const i=line.indexOf(":");if(i<0)continue;const k=line.slice(0,i).trim();if(k!==key)continue;let v=line.slice(i+1).trim().replace(/^["\']|["\']$/g,"");if(v==="true")return true;if(v==="false")return false;if(v==="null"||v==="~")return null;if(/^[-+]?\d+(\.\d+)?$/.test(v))return Number(v);return v}return undefined}
function parseLoose(text){try{return JSON.parse(text)}catch(e){}return{schema:yamlScalar(text,"schema"),benchmark_id:yamlScalar(text,"benchmark_id"),kit_complete:yamlScalar(text,"kit_complete"),expected_bundles:yamlScalar(text,"expected_bundles"),valid_bundles:yamlScalar(text,"valid_bundles"),evidence_publishable:yamlScalar(text,"evidence_publishable"),evidence_status:yamlScalar(text,"evidence_status"),_rawOnly:true}}
function setSummary(){q("#benchmarkId").textContent=current.benchmark_id??"—";q("#kitComplete").textContent=current.kit_complete===true?"YES":current.kit_complete===false?"NO":"—";q("#publishable").textContent=current.evidence_publishable===true?"YES":current.evidence_publishable===false?"NO":"—";q("#evidenceStatus").textContent=current.evidence_status??"—";q("#status").textContent=current===demo?"DEMO CONTRACT":(current.evidence_publishable?"PUBLISHABLE":"INSPECTION MODE");q("#raw").textContent=rawText}
function rows(items,cols){if(!items?.length)return '<p class="muted">No structured entries available in this view. Raw YAML is still preserved below.</p>';return '<table><thead><tr>'+cols.map(c=>"<th>"+esc(c[0])+"</th>").join("")+"</tr></thead><tbody>"+items.map(x=>"<tr>"+cols.map(c=>"<td>"+esc(x[c[1]])+"</td>").join("")+"</tr>").join("")+"</tbody></table>"}
function show(step){document.querySelectorAll(".chain button").forEach(b=>b.classList.toggle("active",b.dataset.step===step));const c=current.candidates||[],inputs=current.inputs||[],bundleRows=c.flatMap(x=>(x.bundles||[]).map(b=>Object.assign({},b,{candidate:x.name,plan_id:x.plan_id,runtime:x.runtime,benchmark_host:x.benchmark_host})));const panel=q("#panel");if(step==="decision")panel.innerHTML="<h2>Precommitted decision</h2><p>The durable object is not “the planner was smart”; it is the exact plan identity that existed before performance evidence was observed.</p>"+rows(c,[["Candidate","name"],["Plan ID","plan_id"],["Host","benchmark_host"],["Runtime","runtime"]]);if(step==="inputs")panel.innerHTML="<h2>Frozen inputs</h2><p>These hashes bind the experiment to the infrastructure/workload material that the claim says it used.</p>"+rows(inputs,[["Role","role"],["Path","path"],["SHA-256","sha256"]]);if(step==="execution")panel.innerHTML="<h2>Execution identity</h2><p>Each retained bundle should make source, executable, runtime, host and capture identity independently inspectable.</p>"+rows(bundleRows,[["Candidate","candidate"],["Plan","source_plan_id"],["Source","source_commit"],["Binary SHA-256","binary_sha256"],["Captured","captured_at"]]);if(step==="evidence")panel.innerHTML="<h2>Raw evidence</h2><p>Claims remain reviewable only while their underlying BenchmarkBundles are retained and hash-bound.</p>"+rows(bundleRows,[["Candidate","candidate"],["Bundle","path"],["SHA-256","sha256"],["Benchmark","benchmark_id"]]);if(step==="claim")panel.innerHTML='<h2>Claim gate</h2><p><strong class="'+(current.evidence_publishable?"ok":"bad")+'">'+(current.evidence_publishable?"PUBLISHABLE":"NOT PUBLISHABLE")+'</strong></p><p>Status: '+esc(current.evidence_status)+'</p><pre>'+esc(JSON.stringify(current.report??{},null,2))+"</pre>";if(step==="verify")panel.innerHTML="<h2>Independent verification</h2><p>The UI never upgrades evidence to truth. Re-run verification against the materialized audit root and reject on hash, identity, report or publishability mismatch.</p><code>meshfit benchmark-verify-proof benchmark-proof.yaml --root &lt;materialized-kit&gt; --require-publishable</code>"}
q("#file").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;rawText=await f.text();current=parseLoose(rawText);setSummary();show("decision")});
q("#demo").addEventListener("click",()=>{current=demo;rawText=JSON.stringify(demo,null,2);setSummary();show("decision")});
q("#copy").addEventListener("click",()=>navigator.clipboard?.writeText(rawText));
document.querySelectorAll(".chain button").forEach(b=>b.addEventListener("click",()=>show(b.dataset.step)));
setSummary();show("decision");